baseURL = 'http://hortenlyd.no/'
languageCode = 'nb'
title = 'Horten Lyd'
theme = 'hortenlydTheme'
pluralizelisttitles = false
[params]
  description = "Vi leverer lyd og produksjoner fra smått til stort på Østlandet"
